/**
 * Ad Blocking Engine for Aegis Browser
 * Blocks ads, trackers, and malware domains
 */

// Common ad/tracker domain patterns
const adDomains = new Set([
    // Google Ads
    'googlesyndication.com',
    'googleadservices.com',
    'doubleclick.net',
    'doubleclick.com',
    'googletagmanager.com',
    'googletagservices.com',
    'googlesyndication.com',
    'googleads.g.doubleclick.net',
    'pagead2.googlesyndication.com',
    'adservice.google.com',

    // Facebook/Meta
    'facebook.com/tr',
    'connect.facebook.net/en_US/fbevents.js',
    'pixel.facebook.com',

    // Analytics & Tracking
    'analytics.google.com',
    'google-analytics.com',
    'googleanalytics.com',
    'hotjar.com',
    'mixpanel.com',
    'segment.io',
    'segment.com',
    'amplitude.com',
    'heap.io',
    'fullstory.com',
    'crazyegg.com',
    'mouseflow.com',
    'clicktale.net',
    'luckyorange.com',

    // Ad Networks
    'adnxs.com',
    'advertising.com',
    'rubiconproject.com',
    'pubmatic.com',
    'openx.net',
    'casalemedia.com',
    'criteo.com',
    'criteo.net',
    'taboola.com',
    'outbrain.com',
    'mgid.com',
    'revcontent.com',
    'adroll.com',
    'adsrvr.org',
    'adtechus.com',
    'advertising.com',
    'bidswitch.net',
    'contextweb.com',
    'lijit.com',
    'liveintent.com',
    'mathtag.com',
    'media.net',
    'moatads.com',
    'nexac.com',
    'quantserve.com',
    'scorecardresearch.com',
    'sharethrough.com',
    'simpli.fi',
    'spotxchange.com',
    'tribalfusion.com',
    'turn.com',
    'undertone.com',
    'yieldmo.com',
    'zedo.com',

    // Pop-up/Pop-under
    'popads.net',
    'popcash.net',
    'propellerads.com',
    'popmyads.com',
    'popunder.net',

    // Malware/Suspicious
    'clicksor.com',
    'clicksor.net',
    'trafficjunky.com',
    'exoclick.com',
    'juicyads.com',

    // Other Trackers
    'bing.com/bat.js',
    'bat.bing.com',
    'sc-static.net',
    'snapchat.com/add',
    'static.ads-twitter.com',
    'ads-twitter.com',
    't.co/i/adsct',
    'analytics.twitter.com',
    'ads.linkedin.com',
    'px.ads.linkedin.com',
    'analytics.tiktok.com',
    'ads.tiktok.com',

    // Common CDN-hosted ads
    'cdn.taboola.com',
    'cdn.outbrain.com',

    // Fingerprinting
    'fingerprintjs.com',
    'cdn.jsdelivr.net/npm/@aspect/fingerprintjs',

    // Error Tracking / Analytics (often used for tracking)
    'sentry.io',
    'sentry-cdn.com',
    'browser.sentry-cdn.com',
    'ingest.sentry.io',
    'bugsnag.com',
    'd2wy8f7a9ursnm.cloudfront.net', // Bugsnag CDN
    'notify.bugsnag.com',
    'sessions.bugsnag.com',
    'app.bugsnag.com',

    // Yandex
    'mc.yandex.ru',
    'yandex.ru/metrika',
    'metrika.yandex.ru',
    'metrica.yandex.com',
    'metrica.yandex.ru',
    'an.yandex.ru',
    'yandexadexchange.net',
    'yabs.yandex.ru',
    'advertising.yandex.ru',
    'direct.yandex.ru',
    'adfox.yandex.ru',
    'yastatic.net/pcode',
    'yastatic.net/share2',

    // Additional trackers for better coverage
    'newrelic.com',
    'nr-data.net',
    'bam.nr-data.net',
    'js-agent.newrelic.com',
    'logrocket.com',
    'cdn.logrocket.io',
    'r.logrocket.io',
    'datadog-logs.com',
    'browser-intake-datadoghq.com',
    'raygun.io',
    'raygun4js.raygun.com',
    'rollbar.com',
    'cdn.rollbar.com',
    'trackjs.com',
    'cdn.trackjs.com',
    'errorception.com',
    'airbrake.io',
    'notifier.airbrake.io',

    // Flash/Rich Media Ad Networks
    'flashtalking.com',
    'serving.flashtalking.com',
    'cdn.flashtalking.com',
    'sizmek.com',
    'bs.serving-sys.com',
    'serving-sys.com',
    'ds.serving-sys.com',
    'eyeblaster.com',
    'mediamind.com',
    'pointroll.com',
    'unicast.com',
    'eyewonder.com',
    'atlas.com',
    'atdmt.com',
    'adnxs-simple.com',
    'innovid.com',
    'celtra.com',
    'jivox.com',
    'flite.com',
    'mixpo.com',

    // Amazon Ads
    'amazon-adsystem.com',
    'aax.amazon-adsystem.com',
    'z-na.amazon-adsystem.com',
    'fls-na.amazon-adsystem.com',
    's.amazon-adsystem.com',
    'c.amazon-adsystem.com',
    'aax-us-east.amazon-adsystem.com',
    'aax-eu.amazon-adsystem.com',
    'aan.amazon.com',
    'assoc-amazon.com',
    'associates-amazon.com',
    'amazonadsi.com',
    'device-metrics-us.amazon.com',
    'device-metrics-us-2.amazon.com',
    'unagi.amazon.com',
    'unagi-na.amazon.com',

    // AdColony
    'adcolony.com',
    'ads.adcolony.com',
    'adc3-launch.adcolony.com',
    'events3alt.adcolony.com',
    'wd.adcolony.com',
    'androidads23.adcolony.com',

    // FreshWorks Analytics
    'freshworks.com',
    'freshmarketer.com',
    'cdn.freshmarketer.com',
    'widget.freshworks.com',
    'euc-widget.freshworks.com',
    'ind-widget.freshworks.com',
    'aus-widget.freshworks.com',
    'wchat.freshchat.com',
    'assetscdn-wchat.freshchat.com',
    'freshdesk.com',
    'assets.freshdesk.com',

    // Stats WP Plugin
    'stats.wp.com',
    'pixel.wp.com',
    'public-api.wordpress.com/rest/v1.1/tracks',
    'widgets.wp.com',
    's0.wp.com',
    's1.wp.com',
    's2.wp.com',

    // LuckyOrange (all subdomains)
    'luckyorange.com',
    'luckyorange.net',
    'upload.luckyorange.net',
    'cs.luckyorange.net',
    'settings.luckyorange.net',
    'realtime.luckyorange.com',
    'api.luckyorange.com',
    'w1.luckyorange.com',

    // Sentry (expanded)
    'sentry.io',
    'sentry-cdn.com',
    'browser.sentry-cdn.com',
    'ingest.sentry.io',
    'app.getsentry.com',
    'getsentry.com',
    'o0.ingest.sentry.io',

    // Social Trackers
    'platform.twitter.com/widgets.js',
    'syndication.twitter.com',
    'cdn.syndication.twimg.com',
    'platform.linkedin.com',
    'snap.licdn.com',
    'px.ads.linkedin.com',
    'www.linkedin.com/px',
    'platform.instagram.com',
    'connect.facebook.net',
    'staticxx.facebook.com',
    'pixel.facebook.com',
    'tr.facebook.com',
    'graph.facebook.com',
    'business.facebook.com',
    'an.facebook.com',
    'web.facebook.com',
    'pinterest.com/ct.html',
    'ct.pinterest.com',
    'widgets.pinterest.com',
    'log.pinterest.com',
    'trk.pinterest.com',
    'api.pinterest.com/v3/pidgets',
    's.pinimg.com/ct',
    'reddit.com/api/info.json',
    'events.reddit.com',
    'rereddit.com',
    'alb.reddit.com',
    'd.reddit.com',
    'static.tumblr.com/cszbebq',
    'assets.tumblr.com',

    // Mix (formerly StumbleUpon)
    'mix.com',
    'stumbleupon.com',
    'su.pr',
    'badge.stumbleupon.com',
    'www.stumbleupon.com/badge',
    'platform.stumbleupon.com',

    // OEMs (Device Manufacturers Tracking)
    'samsungads.com',
    'ads.samsung.com',
    'samsungadhub.com',
    'smetrics.samsung.com',
    'samsung-gaconnector.appspot.com',
    'analytics.s-onetag.com',
    'xiaomi.com/remote/analytics',
    'tracking.miui.com',
    'data.mistat.xiaomi.com',
    'sdkconfig.ad.xiaomi.com',
    'huawei.com/privacy',
    'hicloud.com',
    'ads.oppomobile.com',
    'adsfs.oppomobile.com',
    'bdapi-ads.realmemobile.com',
    'onead.realme.com',
    'iot-logser.realme.com',
    'analytics.vivo.com.cn',
    'ads.vivo.com.cn',

    // Additional commonly missed trackers
    'adform.com',
    'adform.net',
    'adsymptotic.com',
    'agkn.com',
    'bluekai.com',
    'bounceexchange.com',
    'branch.io',
    'cdn.branch.io',
    'app.link',
    'branchster.app.link',
    'chartbeat.com',
    'chartbeat.net',
    'static.chartbeat.com',
    'clarity.ms',
    'www.clarity.ms',
    'demdex.net',
    'dmp.demdex.net',
    'everesttech.net',
    'exelator.com',
    'ib.adnxs.com',
    'igodigital.com',
    'krxd.net',
    'beacon.krxd.net',
    'cdn.krxd.net',
    'marketo.com',
    'mktoresp.com',
    'munchkin.marketo.net',
    'omtrdc.net',
    'dpm.demdex.net',
    'pardot.com',
    'pi.pardot.com',
    'go.pardot.com',
    'quantcast.com',
    'pixel.quantserve.com',
    'salesforce.com/servlet',
    'exacttarget.com',
    'sc.omtrdc.net',
    'tapad.com',
    'thetradedesk.com',
    'match.adsrvr.org',
    'insight.adsrvr.org',
    'twitter.com/i/jot',
    'urchin.js',
    'userzoom.com',
    'm.userzoom.com',
    'cdn5.userzoom.com',
    'vimeocdn.com/js/froogaloop2.min.js',
    'yahoo.com/b',
    'yldbt.com',
    'cdn.yldbt.com',
    'zemanta.com',

    // Amazon S3 ad/analytics buckets
    'adtago.s3.amazonaws.com',
    'advice-ads.s3.amazonaws.com',
    'analytics.s3.amazonaws.com',
    'analyticsengine.s3.amazonaws.com',

    // Twitter/X ads API
    'ads-api.twitter.com',

    // LinkedIn analytics
    'analytics.pointdrive.linkedin.com',

    // Pinterest ads
    'ads.pinterest.com',

    // TikTok expanded
    'business-api.tiktok.com',
    'log.byteoversea.com',
    'analytics-sg.tiktok.com',
    'ads-api.tiktok.com',
    'ads-sg.tiktok.com',

    // Yahoo expanded
    'geo.yahoo.com',
    'analytics.query.yahoo.com',
    'udcm.yahoo.com',
    'log.fc.yahoo.com',
    'partnerads.ysm.yahoo.com',
    'analytics.yahoo.com',
    'gemini.yahoo.com',
    'adtech.yahooinc.com',
    'ads.yahoo.com',

    // Yandex expanded
    'adfstat.yandex.ru',
    'appmetrica.yandex.ru',
    'extmaps-api.yandex.net',
    'offerwall.yandex.net',

    // Unity Ads
    'unityads.unity3d.com',
    'adserver.unityads.unity3d.com',
    'auction.unityads.unity3d.com',
    'webview.unityads.unity3d.com',
    'config.unityads.unity3d.com',

    // Realme expanded
    'bdapi-in-ads.realmemobile.com',
    'iot-eu-logser.realme.com',

    // Xiaomi expanded
    'sdkconfig.ad.intl.xiaomi.com',
    'api.ad.xiaomi.com',
    'data.mistat.india.xiaomi.com',
    'data.mistat.rus.xiaomi.com',
    'tracking.rus.miui.com',

    // Samsung expanded
    'samsung-com.112.2o7.net',
    '112.2o7.net',
    'nmetrics.samsung.com',
    'analytics-api.samsunghealthcn.com',

    // Oppo expanded
    'adx.ads.oppomobile.com',
    'ck.ads.oppomobile.com',
    'data.ads.oppomobile.com',

    // Huawei expanded
    'metrics.data.hicloud.com',
    'metrics2.data.hicloud.com',
    'grs.hicloud.com',
    'logservice.hicloud.com',
    'logservice1.hicloud.com',
    'logbak.hicloud.com',

    // OnePlus
    'open.oneplus.net',
    'click.oneplus.cn',

    // Apple ads/analytics
    'api-adservices.apple.com',
    'iadsdk.apple.com',
    'metrics.mzstatic.com',
    'metrics.icloud.com',
    'notes-analytics-events.apple.com',
    'books-analytics-events.apple.com',
    'weather-analytics-events.apple.com',

    // Reddit expanded
    'events.redditmedia.com',

    // YouTube ads
    'ads.youtube.com',

    // CanYouBlockIt Extreme Test domains
    'coosync.com',
    'npttech.com',
    'insurads.com',
    'ad.doubleclick.net',
    'static.doubleclick.net',
    'stats.g.doubleclick.net',
    'cm.g.doubleclick.net',
    'pubads.g.doubleclick.net',
    'securepubads.g.doubleclick.net',
    'bid.g.doubleclick.net',
    'googleads.g.doubleclick.net',
    'googleads4.g.doubleclick.net',
    'www3.doubleclick.net',
    'ad-g.doubleclick.net',
    's0.2mdn.net',
    's1.2mdn.net',
    '2mdn.net',
    'tpc.googlesyndication.com',
    'pagead2.googleadservices.com',
    'www.googleadservices.com',
    'fundingchoicesmessages.google.com',
    'contributor.google.com',
    'ogs.google.com',

    // Extreme Test - Ad Networks
    'adtrue.com',
    'adfox.ru',
    'adhigh.net',
    'adhese.com',
    'adition.com',
    'adk2.co',
    'adkernel.com',
    'adlooxtracking.com',
    'admixer.net',
    'adnium.com',
    'adocean.pl',
    'adpone.com',
    'adreactor.com',
    'ads-blocker.com',
    'adspyglass.com',
    'adsterra.com',
    'adthrive.com',
    'adtiger.de',
    'adtriba.com',
    'advanced-ads.com',
    'adventori.com',
    'adversal.com',
    'adverticum.net',
    'advertisingiq.com',
    'adyoulike.com',
    'adzerk.net',
    'afalcdn.com',
    'affec.tv',
    'aidata.co',
    'aimatch.com',
    'airpush.com',
    'altitude-arena.com',
    'amgload.net',
    'amobee.com',
    'anyclip.com',
    'anymind360.com',
    'apester.com',
    'appier.net',
    'appsflyer.com',
    'aps.amazon.com',
    'aps.amazon-adsystem.com',
    'au.kwai.com',
    'avantisvideo.com',

    // Extreme Test - Trackers
    'b-cdn.net',
    'bannerflow.com',
    'batch.com',
    'beachfront.com',
    'beemray.com',
    'betweendigital.com',
    'bidgear.com',
    'bidmachine.io',
    'bidswitch.com',
    'bidtellect.com',
    'bidtheatre.com',
    'bidverdrd.com',
    'bidr.io',
    'bitmedianetwork.com',
    'bizible.com',
    'bkrtx.com',
    'blueconic.net',
    'boldwin.com',
    'bombora.com',
    'bouncex.net',
    'brainlyads.com',
    'brightroll.com',
    'browsi.com',
    'btloader.com',
    'bttrack.com',
    'bumlam.com',
    'burt.io',
    'buysellads.com',

    // Extreme Test - More Networks
    'c1exchange.com',
    'carambo.la',
    'carbonads.com',
    'cardlytics.com',
    'casualgames.com',
    'cdn-sitescout.com',
    'cedexis.com',
    'cetadata.com',
    'channeladvisor.com',
    'choosedigital.com',
    'clarium.global',
    'clearcutads.com',
    'clickadu.com',
    'clickagy.com',
    'clickfuse.com',
    'clickiocdn.com',
    'clicktripz.com',
    'client.fx-exchange.com',
    'cliipa.com',
    'cnevids.com',
    'cntdy.mobi',
    'cogocast.net',
    'coinhive.com',
    'coinhive-proxy.com',
    'coinpot.co',
    'comboapp.com',
    'combocdn.com',
    'como.com',
    'company-target.com',
    'conative.io',
    'connatix.com',
    'connexity.net',
    'connectad.io',
    'contentexchange.me',
    'contextweb.com',
    'converge-digital.com',
    'converto.com',
    'conviva.com',
    'cooladata.com',
    'corbula.com',
    'cordial.com',
    'creative-serving.com',
    'creativecdn.com',
    'crta.io',
    'crtv.link',
    'crwdcntrl.net',
    'ctasnet.com',
    'ctnsnet.com',
    'cuebiq.com',
    'cxense.com',

    // Extreme Test - D-F
    'datonics.com',
    'deepintent.com',
    'demandbase.com',
    'deqwas.net',
    'dfp-cdn.com',
    'digitru.st',
    'districtm.io',
    'djaxadserver.com',
    'dmtracker.com',
    'dotomi.com',
    'doubleverify.com',
    'dsp.io',
    'dspcdn.com',
    'dwin1.com',
    'dynamic-ads.wikia.com',
    'dynamicyield.com',
    'e-planning.net',
    'earnify.com',
    'effectivemeasure.net',
    'eloqua.com',
    'email-ads.com',
    'emerse.com',
    'engageclick.com',
    'engagebdr.com',
    'ensighten.com',
    'enviousdigital.com',
    'epnt.com',
    'eqads.com',
    'ero-advertising.com',
    'essens.no',
    'etahub.com',
    'ethicalads.io',
    'eulerian.net',
    'evergage.com',
    'evyy.net',
    'exdynsrv.com',
    'exponential.com',
    'extreme-dm.com',
    'extremereach.io',
    'eyeota.net',
    'eyeviewads.com',
    'f5lt.com',
    'faktor.io',
    'fam-ad.com',
    'fastly-insights.com',
    'fb.me',
    'fidelity-media.com',
    'fiftyt.com',
    'flashpops.eu',
    'flurry.com',
    'footprint.net',
    'foresee.com',
    'fpctraffic.com',
    'free-counter.co.uk',
    'freeskreen.com',
    'freewheel.tv',
    'freewheel.com',
    'fusionads.net',
    'fyber.com',

    // Extreme Test - G-L
    'gammaplatform.com',
    'gcs.io',
    'geniusjs.com',
    'geoedge.be',
    'getclicky.com',
    'getintent.com',
    'glassboxdigital.io',
    'gmads.net',
    'gmossp-sp.jp',
    'go2cloud.org',
    'gogobogo.com',
    'gokumarket.com',
    'goldbach.com',
    'goo.ne.jp',
    'gosquared.com',
    'gq1d.com',
    'gqevu.com',
    'grapeshot.co.uk',
    'gravityrd-services.com',
    'groupm.com',
    'grvcdn.com',
    'gsspcln.jp',
    'gtmedia.tv',
    'gumgum.com',
    'gwallet.com',
    'hbopenbid.pubmatic.com',
    'heap.io',
    'heapanalytics.com',
    'hilltopads.net',
    'histats.com',
    'hit.gemius.pl',
    'honeybadger.io',
    'honeybadger-cdn.io',
    'hottraffic.net',
    'hsoub.com',
    'htl.bid',
    'hubspot.com',
    'hubspotusercontent.com',
    'hymnal.com',
    'hyprmx.com',
    'i-mobile.co.jp',
    'ibillboard.com',
    'ib.mookie1.com',
    'id5-sync.com',
    'igodigital.com',
    'im-apps.net',
    'impact.com',
    'impactradius.com',
    'impactradius-event.com',
    'implicitr.com',
    'impressiondesk.com',
    'improvedigital.com',
    'indexww.com',
    'infernotions.net',
    'infinite-folds.com',
    'infra-ad.com',
    'infolinks.com',
    'inmobi.com',
    'inner-active.mobi',
    'innity.com',
    'insightexpressai.com',
    'insnw.net',
    'inspectlet.com',
    'insticator.com',
    'instinctiveads.com',
    'instreamads.com',
    'intelliad.de',
    'intellitxt.com',
    'intentiq.com',
    'intentmedia.net',
    'intergi.com',
    'intergient.com',
    'intermarkets.net',
    'interrogare.de',
    'intextads.com',
    'invitemedia.com',
    'iogous.com',
    'ipredictive.com',
    'iqzone.com',
    'ironsrc.com',
    'ironsource.com',
    'isocket.com',
    'ispot.tv',
    'iterable.com',
    'ixiaa.com',
    'j.srk.ai',
    'jems.io',
    'jewishcontentnetwork.com',
    'js.ad-score.com',
    'jsf.io',
    'jsrdn.com',
    'juicyads.net',
    'justpremium.com',
    'kaltura.com',
    'kameleoon.eu',
    'kanade-ad.net',
    'keywee.co',
    'keywordblocks.com',
    'kinzoo.com',
    'kissmetrics.com',
    'kixer.com',
    'kn3.net',
    'kochava.com',
    'komona.com',
    'kontera.com',
    'kpushtag.com',
    'kwanko.com',
    'ladesk.com',
    'launchdarkly.com',
    'leadforensics.com',
    'leadid.com',
    'leadpages.net',
    'leanplum.com',
    'legolas-media.com',
    'lfstmedia.com',
    'lifestreet.com',
    'liftoff.io',
    'lijit.com',
    'linkedin-ei.com',
    'linksredirect.com',
    'list.ru',
    'liveadexchanger.com',
    'liveconnect.com',
    'livefyre.com',
    'liverail.com',
    'lockerdome.com',
    'loop-media.co',
    'lp4.io',
    'ltassrv.com',
    'luxup.ru',
    'lytics.io',

    // Extreme Test - M-P
    'm6r.eu',
    'madgic.com',
    'mainroll.com',
    'marfeelrev.com',
    'marinsoftware.com',
    'marketgid.com',
    'maxmind.com',
    'mazu.co',
    'mbps.io',
    'medallia.com',
    'mediabong.com',
    'mediaforge.com',
    'mediasmart.es',
    'mediav.com',
    'mediavine.com',
    'mediawallah.com',
    'meetrics.net',
    'memprof.com',
    'metaffiliation.com',
    'metrigo.com',
    'mgid.com',
    'miaozhen.com',
    'microad.jp',
    'mintegral.com',
    'mixadvert.com',
    'mjolnir.media',
    'ml314.com',
    'mmnetwork.mobi',
    'moartraffic.com',
    'moatads.com',
    'mobads.co',
    'mobfox.com',
    'mobilefuse.com',
    'mobilelead.com',
    'mobiletheory.com',
    'moblivious.com',
    'mobpro.com',
    'mobvista.com',
    'mociads.com',
    'mocean.mobi',
    'monetate.net',
    'monetizely.com',
    'mozo.com.au',
    'mparticle.com',
    'msads.net',
    'mtrcs.samba.tv',
    'munchkin.com',
    'mybuys.com',
    'mxpnl.net',
    'mxptint.net',
    'myads.telkomsel.com',
    'myadoptimizer.com',
    'myretargetingnetwork.com',
    'n2media.net',
    'narrative.io',
    'nativeads.com',
    'navdmp.com',
    'navegg.com',
    'nearme.co',
    'nend.net',
    'netdna-ssl.com',
    'netgear.live',
    'netmng.com',
    'netshelter.net',
    'newsroom.bi',
    'newstarads.com',
    'nextoffer.net',
    'nexus.ensighten.com',
    'nielsen.com',
    'Nielsen-online.com',
    'npttech.com',
    'nugg.ad',
    'nuggad.net',
    'numberlytics.com',
    'nutriads.com',
    'o333o.com',
    'oaseuro.com',
    'oath.com',
    'oas.outbrain.com',
    'obitrk.com',
    'objxml.com',
    'ob-rt.com',
    'ogury.com',
    'omappapi.com',
    'omeda.com',
    'omnisnippet.com',
    'omnisrc.com',
    'omnivirt.com',
    'onads.io',
    'oncrypt.co',
    'onesignal.com',
    'onscroll.com',
    'ontrq.com',
    'openexchangerates.org',
    'openrtb.tubemogul.com',
    'opti-digital.com',
    'optimatic.com',
    'optimise-media.com',
    'optimix.asia',
    'optimizely.com',
    'otto-js.com',
    'outbrainimg.com',
    'owneriq.net',
    'ownlocal.com',
    'p0y.io',
    'pages.email.salesforce.com',
    'pagescorr.com',
    'papayads.com',
    'parfairads.com',
    'parsely.com',
    'partnerize.com',
    'payclick.com',
    'pbid.pro',
    'pbstck.com',
    'peak226.com',
    'peer39.com',
    'pemsrv.com',
    'pennyweb.com',
    'perfectaudience.com',
    'performgroup.com',
    'perion.com',
    'permutive.com',
    'pf.entertainow.com',
    'pgmediaserve.com',
    'phluant.com',
    'piano.io',
    'picatcha.com',
    'pingdom.net',
    'pixels.ai',
    'pixfuture.net',
    'placed.com',
    'plausible.io',
    'playground.xyz',
    'plista.com',
    'pmc.com',
    'pocketmath.com',
    'podnova.com',
    'polyfill.io',
    'popjoy.io',
    'popmyads.net',
    'popupmoney.com',
    'post.cr',
    'postrelease.com',
    'ppjol.net',
    'praized.com',
    'prebid.org',
    'preciso.net',
    'predicta.net',
    'presage.io',
    'primis.tech',
    'pro-market.net',
    'proclivitysystems.com',
    'proofpoint.com',
    'prospecteye.com',
    'prosperent.com',
    'providertrust.com',
    'provify.com',
    'ps-i.net',
    'pssupport.com',
    'psyma.com',
    'pub.network',
    'publitas.com',
    'pubmatic.com',
    'pubnation.com',
    'pubsec.io',
    'pulpix.com',
    'pulsemgr.com',
    'pushengage.com',
    'pushnami.com',
    'pushwoosh.com',
    'px.owneriq.net',

    // Extreme Test - Q-Z
    'qcx.io',
    'qedev.com',
    'quantcount.com',
    'quantum-advertising.com',
    'qubit.com',
    'quertle.com',
    'quora.com',
    'qwertee.eu',
    'r1-cdn.net',
    'radiateb2b.com',
    'radarurl.com',
    'rampidx.com',
    'rapidswitch.co.uk',
    'rate-exchange.com',
    'rawnet.com',
    'rczblog.com',
    'rdtk.io',
    'reachmax.cn',
    'readpeak.com',
    'realclever.com',
    'realytics.io',
    'reamp.com',
    'reconvert.com',
    'recrue.co',
    'redintel.com',
    'redirectvoluum.com',
    'redshell.io',
    'reembed.com',
    'refersion.com',
    'relevad.com',
    'reltime.live',
    'remarketing.com',
    'renewal-net.com',
    'researchnow.com',
    'resilient.cc',
    'retailmenot.com',
    'retargetly.com',
    'returnpath.net',
    'revcatch.com',
    'revive-adserver.com',
    'revjet.com',
    'rfihub.com',
    'rhythmone.com',
    'richmedia.yahoo.com',
    'richpush.co',
    'ritzcarlton.com',
    'rlets.com',
    'rlcdn.com',
    'rmtag.com',
    'rnmd3.com',
    'rogersmedia.ca',
    'rokkan.com',
    'roku.com',
    'royalty.io',
    'rpxnow.com',
    'rr.mtrcs.samba.tv',
    'rtb.gumgum.com',
    'rtbsuperhub.com',
    'rtbvideoads.com',
    'rtmark.net',
    'rubiconproject.com',
    'rumble.cloud',
    'run.admost.com',
    'rv.eaudio.com',
    'ryzesolutions.net',
    's81c.com',
    'saambaa.com',
    'sabio.us',
    'sadadserv.com',
    'salecycle.com',
    'salesforceliveagent.com',
    'saluslabs.com',
    'samplicio.us',
    'sape.ru',
    'sapesolutions.net',
    'sarv.com',
    'sas.com',
    'saymedia.com',
    'sback.net',
    'scanmedios.com',
    'scndx.uk',
    'scoot.scootwifi.com',
    'screenpopper.com',
    'sdk.streamrail.com',
    'sdkbox.com',
    'seadform.net',
    'seasonvar.ru',
    'secura.net',
    'segment.com',
    'selectmedia.asia',
    'selly.com',
    'semknox.com',
    'sensic.net',
    'seopedia.lt',
    'servedbyadbutler.com',
    'servedbytrackingdesk.com',
    'servethis.com',
    'serving-sys.com',
    'sessions.bugsnag.com',
    'setv.adap.tv',
    'shareasale.com',
    'sharecore.net',
    'shinystat.com',
    'shortstack.com',
    'showheroes.com',
    'shrt.ai',
    'sibautomation.com',
    'sift.co',
    'siftscience.com',
    'signal.co',
    'signifyd.com',
    'silverpop.com',
    'simpli.fi',
    'singular.net',
    'singlespotapp.com',
    'sitechecker.pro',
    'siteimprove.com',
    'siteintercept.qualtrics.com',
    'sitescout.com',
    'sjpf.io',
    'skimresources.com',
    'sliads.com',
    'slideinn.com',
    'slidemyads.com',
    'slimspots.com',
    'slopeways.com',
    'smartadserver.com',
    'smartclick.net',
    'smarterremarketer.net',
    'smartsheet.com',
    'smct.co',
    'smilewanted.com',
    'smoozd.com',
    'smrtb.com',
    'snacktools.com',
    'snapads.com',
    'snigelweb.com',
    'snoobi.com',
    'so-net.ne.jp',
    'sociaplus.com',
    'socialknxss.com',
    'sociomantic.com',
    'sokrati.com',
    'solocpm.com',
    'sonobi.com',
    'sortable.com',
    'soulx.net',
    'souvrn.com',
    'sovrn.com',
    'sparklit.com',
    'sparkstudios.com',
    'sparwelt.de',
    'specifimedia.co.uk',
    'spectoo.com',
    'speedomizer.com',
    'speedshiftmedia.com',
    'spidasweb.com',
    'spike.com',
    'splashthat.com',
    'splitbrain.org',
    'spot.im',
    'spoteffects.net',
    'spotify.com/ad',
    'spotxchange.com',
    'springserve.com',
    'spry.cx',
    'sqwat.io',
    'stackadapt.com',
    'start.me',
    'startapp.com',
    'startappexchange.com',
    'startmobile.net',
    'stat24.com',
    'static.hitbox.tv',
    'stickyadstv.com',
    'stileproject.com',
    'storydoc.io',
    'stpn.co',
    'stpn.io',
    'stream-ad.com',
    'strikead.com',
    'stroeer.ms',
    'strossle.com',
    'sumo.com',
    'sumologic.com',
    'sumome.com',
    'superad.tech',
    'superfish.com',
    'supersonicads.com',
    'survata.com',
    'surveygizmo.com',
    'surveymonkey.com',
    'susqbang.com',
    'swelen.com',
    'swiftype.com',
    'synacor.com',
    'syndacast.com',
    'synergy-e.com',
    't4ft.de',
    'tagcommander.com',
    'taggify.net',
    'tail.digital',
    'talkable.com',
    'tamgrt.com',
    'tanx.com',
    'tapfiliate.com',
    'tapinfluence.com',
    'tapjoy.com',
    'tapsense.com',
    'taptapad.com',
    'targetspot.com',
    'taskanalytics.com',
    'tealium.com',
    'tealiumiq.com',
    'techlab-cdn.com',
    'techtarget.com',
    'tedivm.com',
    'teenyzing.com',
    'telemetry.js',
    'telesec.net',
    'tellapart.com',
    'terraclicks.com',
    'textad.net',
    'thanksandgoodnight.com',
    'thedigitrust.com',
    'themediagrid.com',
    'thepermit.net',
    'thepundits.com',
    'thirdpartytracking.com',
    'thisis.media',
    'throughline.co',
    'thunderhead.com',
    'ticketmaster.com',
    'tids.io',
    'tinypass.com',
    'tiuun.com',
    'tns-counter.ru',
    'tntclix.co.uk',
    'toonads.com',
    'top100.rambler.ru',
    'topchainarticles.com',
    'toplist.cz',
    'topsy.com',
    'track.anchorfree.com',
    'trackcmp.net',
    'tracking.pch.com',
    'trackingpro.co',
    'trackmyurl.biz',
    'tracksimple.com',
    'tradedoubler.com',
    'tradelab.fr',
    'tradetracker.net',
    'trafficforce.com',
    'traffichaus.com',
    'trafficleader.com',
    'trafficmp.com',
    'trafficspaces.net',
    'trafficstars.com',
    'trafficzen.com',
    'trajex.com',
    'traktrafficflow.com',
    'travora.com',
    'traveladnetwork.com',
    'travelaudience.com',
    'trbas.com',
    'tremorhub.com',
    'trex.com',
    'trf.ai',
    'trialpay.com',
    'tribegroup.com',
    'triggit.com',
    'truffle.bid',
    'trust.zone',
    'trustpilot.com',
    'trustx.org',
    'tsyndicate.com',
    'tubemogul.com',
    'tumri.net',
    'turn.com',
    'twenga.com',
    'twiago.com',
    'twyn.com',
    'tynt.com',
    'u-ad.info',
    'udmserve.net',
    'ukr.net',
    'unanimis.co.uk',
    'undertone.com',
    'unrulymedia.com',
    'upapi.net',
    'uplandsoftware.com',
    'upsellit.com',
    'urbanairship.com',
    'usabilla.com',
    'usemax.de',
    'usercentricscdn.com',
    'usercentrics.com',
    'userreplay.net',
    'utarget.ru',
    'valueclick.com',
    'valuecommerce.com',
    'valuedopinions.com',
    'vdopia.com',
    'veinteractive.com',
    'velti.com',
    'veritone.com',
    'vertoz.com',
    'vervewireless.com',
    'vespa.ai',
    'vibrantmedia.com',
    'video.oi',
    'videobeet.tv',
    'videogen.io',
    'videoint.io',
    'videoplatform.net',
    'vidoomy.com',
    'view.co.jp',
    'viglink.com',
    'vindico.com',
    'visualdna.com',
    'vli.agency',
    'voicefive.com',
    'voluum.com',
    'vpadn.com',
    'vroomnetwork.com',
    'vs-cdn.com',
    'vtracker.net',
    'vutura.net',
    'w55c.net',
    'wavedash.com',
    'webclicks.net',
    'webface.eu',
    'webgains.com',
    'webmasterplan.com',
    'webspectator.com',
    'webtraxs.com',
    'weborama.com',
    'weborama.fr',
    'webtrekk.net',
    'webtrends.com',
    'whatcounts.com',
    'widespace.com',
    'winmax.com',
    'wknd.ai',
    'wonderpush.com',
    'woopra.com',
    'worldsoft-cms.info',
    'worthathousandwords.com',
    'wow-analytics.ru',
    'wunderloop.net',
    'x.bidswitch.net',
    'xad.com',
    'xertive.com',
    'xiti.com',
    'xlinktracking.com',
    'xnxx-cdn.com',
    'xplosion.de',
    'xtendmedia.com',
    'y1.net',
    'yandexadexchange.net',
    'yashi.com',
    'yellowblue.io',
    'yext.com',
    'yield.com',
    'yieldlab.net',
    'yieldoptimizer.com',
    'yieldpartners.com',
    'yieldtraffic.com',
    'yoc.com',
    'yotpo.com',
    'youramigo.com',
    // 'youtube-nocookie.com', // Removed - this is a legitimate YouTube embed domain, not an ad domain
    'ysance.com',
    'zanox.com',
    'zaps.io',
    'zedo.com',
    'zeotap.com',
    'zergnet.com',
    'zeustechnology.com',
    'ziff.io',
    'zoho.com/salesiq',
    'zopim.com',
    'zqtk.net',

    // CanYouBlockIt Extreme - Random/Obfuscated domains
    '12ezo5v60.com',
    'adsco.re',
    'adscore.com',
    'adscr.co',
    'gvt1.com',
    'gvt2.com',
    'gvt3.com',
    '1rx.io',
    'a-mo.net',
    'aax-eu-dub.amazon.com',
    'aax-fe.amazon.com',
    'aax-us-iad.amazon.com',
    'ab.advertiserurl.com',
    'ad.gt',
    'ad.mo',
    'ad4m.at',
    'adblade.com',
    'adbutler.com',
    'adbuyer.com',
    'adcash.com',
    'addroplet.com',
    'adengage.com',
    'adextent.com',
    'adfarm.mediaplex.com',
    'adflex.net',
    'adglare.net',
    'adgshp.com',
    'adhealers.com',
    'adhitz.com',
    'adicate.com',
    'adingo.jp',
    'adizio.com',
    'adjacency.com',
    'adjug.com',
    'adjuggler.net',
    'adkaora.com',
    'adkeeper.co.kr',
    'adkernel.net',
    'adlegend.com',
    'adlibsolutions.com',
    'adloaded.com',
    'adlogic.com.au',
    'adlsrvc.com',
    'admailtiser.com',
    'admarketplace.com',
    'admarvel.com',
    'admaxim.com',
    'admaximizer.com',
    'admedia.com',
    'admedian.com',
    'admeridian.com',
    'admeta.com',
    'admob.com',
    'admotion.com.ar',
    'admtpmp112.com',
    'admtpmp113.com',
    'admtpmp114.com',
    'adnami.io',
    'adnesis.com',
    'adnet.com',
    'adnet.de',
    'adnetasia.com',
    'adnetinteractive.com',
    'adnext.fr',
    'adnimation.com',
    'adnologies.com',
    'adnotch.com',
    'adnstream.com',
    'ado.pro',
    'adobe.demdex.net',
    'adobedtm.com',
    'adobetm.com',
    'adop.cc',
    'adoptim.com',
    'adorable.io',
    'adorika.com',
    'adotmob.com',
    'adoutput.com',
    'adparlor.com',
    'adpays.com',
    'adpinion.com',
    'adpionier.de',
    'adplans.com',
    'adplayer.com',
    'adplexity.com',
    'adplugg.com',
    'adpnut.com',
    'adpro.com.vn',
    'adproximate.com',
    'adpushup.com',
    'adquerulous.com',
    'adrazzi.com',
    'adreadytractions.com',
    'adrecover.com',
    'adrecreate.com',
    'adrizer.com',
    'adroute.com',
    'adrta.com',
    'adrunnr.com',
    'ads1.msads.net',
    'ads2.msads.net',
    'ads3.msads.net',
    'adsafeprotected.com',
    'adsbynimbus.com',
    'adsbyxyzs123.com',
    'adscience.nl',
    'adscope.com',
    'adsdaq.com',
    'adsfast.com',
    'adsfundi.com',
    'adsfunder.com',
    'adshares.net',
    'adshots.biz',
    'adshuffle.com',
    'adskeeper.co.uk',
    'adskeeper.com',
    'adsmogo.com',
    'adsmonetize.com',
    'adsnative.com',
    'adsoptimal.com',
    'adspeed.net',
    'adsplay.in',
    'adspro.com',
    'adsrevenue.net',
    'adssettings.google.com',
    'adstanding.com',
    'adstars.com',
    'adsteam.com',
    'adstrategy.com',
    'adstreme.com',
    'adstriker.com',
    'adstrix.net',
    'adswiz.com',
    'adswizz.com',
    'adsymptotic.com',
    'adsyndication.com',
    'adsynergy.com',
    'adtarget.me',
    'adtarget.net',
    'adtdy.com',
    'adtech.de',
    'adtegrity.net',
    'adtheorent.com',
    'adthink.com',
    'adtiger.de',
    'adtilt.com',
    'adtng.com',
    'adtoma.com',
    'adtrace.org',
    'adtrade.net',
    'adtrakr.com',
    'adtrix.com',
    'adtrue.com',
    'adtruism.com',
    'adturtle.biz',
    'adultadworld.com',
    'adultswim-ads.com',
    'adunity.com',
    'adups.com',
    'adventive.com',
    'adverclick.com',
    'adverline.com',
    'adverserve.net',
    'advertarium.com.ua',
    'advertica.com',
    'adverticum.net',
    'advertiser.com',
    'advertnative.com',
    'advertory.net',
    'advgr.com',
    'advibe.com',
    'advideo.design',
    'advisormedia.com',
    'advk.ru',
    'advmaker.net',
    'adv-mdn.com',
    'advolution.de',
    'advombat.ru',
    'advon.com',
    'advtrk.com',
    'advtrk.net',
    'adwebster.com',
    'adwhirl.com',
    'adwired.net',
    'adwitserver.com',
    'adwolf.com',
    'adworkmedia.net',
    'adx.io',
    'adxcel.com',
    'adxcore.com',
    'adxpansion.com',
    'adyard.de',
    'adzerk.net',
    'adzerk.s3.amazonaws.com',
    'adzip.co',
    'adzs.nl',
    'adztec.com',
]);

// URL patterns to block (regex)
const adUrlPatterns = [
    // Random/obfuscated ad domain patterns
    /^https?:\/\/[a-z0-9]{8,20}\.(com|net|io|co)\/.*\.(js|gif|png)$/i,
    /[0-9a-f]{20,}/i,  // Long hex strings often used in tracking
    /\/lib\.js$/i,
    /\/tr\//i,
    /\/zavbn\//i,
    /pn[0-9]+uscr/i,
    /vcd[0-9a-f]{20,}/i,
    /\/ads\//i,
    /\/ad\//i,
    /\/adserver/i,
    /\/advert/i,
    /\/banner/i,
    /\/sponsor/i,
    /\/tracking/i,
    /\/tracker/i,
    /\/pixel\./i,
    /\/beacon/i,
    /\/analytics\.js/i,
    /\/gtag\/js/i,
    /\/gtm\.js/i,
    /\/fbevents\.js/i,
    /doubleclick/i,
    /googlesyndication/i,
    /googleadservices/i,
    /pagead/i,
    /adsystem/i,
    /adservice/i,
    /\.ads\./i,
    /\/pop(up|under)/i,
    // Flash/Banner patterns
    /\.swf$/i,
    /\/flash\//i,
    /\/flashads/i,
    /\/flash_ads/i,
    /\/banners?\//i,
    /\/adbanners?/i,
    /\/adbanner/i,
    /\/banner_?ads?/i,
    /\/bannerad/i,
    /\/flash.*\.swf/i,
    /\/adflash/i,
    /\/flashad/i,
    /\/swfobject/i,
    /\/swf_/i,
    /flashtalking/i,
    /\.flv$/i,
    /\/adcontent/i,
    /\/adcreative/i,
    /\/creative.*ad/i,
    /\/rich_?media/i,
    /\/richmedia/i,
    // Sentry patterns
    /sentry\.io/i,
    /\/sentry\//i,
    /sentry-cdn\.com/i,
    /\.sentry\./i,
    // Bugsnag patterns
    /bugsnag/i,
    /\/bugsnag\./i,
    // Yandex patterns
    /mc\.yandex/i,
    /metrika\.yandex/i,
    /metrica\.yandex/i,
    /yandex\.ru\/metrika/i,
    /yabs\.yandex/i,
    /an\.yandex/i,
    /adfox\.yandex/i,
    /direct\.yandex/i,
    /yandexadexchange/i,
    // Error tracking patterns
    /newrelic/i,
    /nr-data\.net/i,
    /logrocket/i,
    /rollbar/i,
    /raygun/i,
    /trackjs/i,
    /airbrake/i,
    /errorception/i,
    /datadog/i,
    /getsentry/i,
    // Amazon ads patterns
    /amazon-adsystem/i,
    /amazonadsi/i,
    /assoc-amazon/i,
    /device-metrics.*amazon/i,
    // AdColony patterns
    /adcolony/i,
    // FreshWorks patterns
    /freshmarketer/i,
    /freshworks.*widget/i,
    /freshchat/i,
    // WordPress stats
    /stats\.wp\.com/i,
    /pixel\.wp\.com/i,
    // LuckyOrange patterns
    /luckyorange/i,
    // Social trackers patterns
    /platform\.twitter/i,
    /syndication\.twitter/i,
    /platform\.linkedin/i,
    /snap\.licdn/i,
    /connect\.facebook/i,
    /pixel\.facebook/i,
    /tr\.facebook/i,
    /business\.facebook/i,
    /ct\.pinterest/i,
    /log\.pinterest/i,
    /trk\.pinterest/i,
    /events\.reddit/i,
    /redditmedia/i,
    // Mix/StumbleUpon
    /stumbleupon/i,
    /badge\.stumbleupon/i,
    // OEM trackers
    /samsungads/i,
    /samsungadhub/i,
    /smetrics\.samsung/i,
    /nmetrics\.samsung/i,
    /112\.2o7\.net/i,
    /tracking\.miui/i,
    /mistat\.xiaomi/i,
    /sdkconfig\.ad\.xiaomi/i,
    /api\.ad\.xiaomi/i,
    /ads\.oppomobile/i,
    /ads\.vivo/i,
    /hicloud\.com/i,
    /oneplus\.net/i,
    /oneplus\.cn/i,
    // Apple tracking
    /api-adservices\.apple/i,
    /iadsdk\.apple/i,
    /metrics\.mzstatic/i,
    /metrics\.icloud/i,
    /-analytics-events\.apple/i,
    // Unity Ads
    /unityads/i,
    /unity3d\.com.*ad/i,
    // Yahoo patterns
    /geo\.yahoo/i,
    /analytics.*yahoo/i,
    /udcm\.yahoo/i,
    /partnerads.*yahoo/i,
    /gemini\.yahoo/i,
    /adtech\.yahooinc/i,
    // TikTok expanded
    /byteoversea/i,
    /business-api\.tiktok/i,
    /ads-api\.tiktok/i,
    /ads-sg\.tiktok/i,
    /analytics-sg\.tiktok/i,
    // Amazon S3 ad buckets
    /adtago\.s3/i,
    /advice-ads\.s3/i,
    /analytics\.s3\.amazonaws/i,
    /analyticsengine\.s3/i,
    // LinkedIn expanded
    /pointdrive\.linkedin/i,
    // Additional patterns
    /\/widget.*share/i,
    /\/share.*button/i,
    /\/social.*plugin/i,
    /\/like.*button/i,
    /chartbeat/i,
    /clarity\.ms/i,
    /quantserve/i,
    /quantcast/i,
    /bluekai/i,
    /krxd\.net/i,
    /demdex/i,
    /omtrdc/i,
    /munchkin\.marketo/i,
    /pardot/i,
    /branch\.io/i,
    /app\.link/i,
    /thetradedesk/i,
    /adsrvr\.org/i,
    /userzoom/i,
    /zemanta/i,
    // Extreme Test patterns
    /coosync/i,
    /npttech/i,
    /insurads/i,
    /2mdn\.net/i,
    /fundingchoices/i,
    /contributor\.google/i,
    /pagead2/i,
    /pubads\.g\.doubleclick/i,
    /securepubads/i,
    /googleads\.g\.doubleclick/i,
    /cm\.g\.doubleclick/i,
    /bid\.g\.doubleclick/i,
    /stats\.g\.doubleclick/i,
    /ad\.doubleclick/i,
    /static\.doubleclick/i,
    // Common ad patterns
    /\/prebid/i,
    /\/gpt\.js/i,
    /\/gpt_mobile/i,
    /\/show_ads/i,
    /\/pagead\/js/i,
    /\/adsense/i,
    /\/adframe/i,
    /\/adfetch/i,
    /\/adload/i,
    /\/adcall/i,
    /\/adrequest/i,
    /\/adtags/i,
    /\/adtech/i,
    /\/adview/i,
    /\/adzone/i,
    /\/a]d\.php/i,
    /\/ads\.php/i,
    /\/ad\.js/i,
    /\/ads\.js/i,
    /getads/i,
    /loadads/i,
    /fetchads/i,
    /displayads/i,
    /\/dfp/i,
    /\/gam\.js/i,
    /\/adup/i,
    /\/widget_static.*\.js/i,
    // Affiliate patterns
    /\/affiliate/i,
    /\/aff_/i,
    /\/afftrack/i,
    /clickid=/i,
    /subid=/i,
    /\/cpa\//i,
    /\/cpv\//i,
    /\/cpm\//i,
    /\/cpc\//i,
    // Popup/Popunder patterns
    /\/popunder/i,
    /\/popup/i,
    /\/pop\.js/i,
    /\/popads/i,
    /\/popcash/i,
    /\/propeller/i,
    /popjs/i,
    // Video ads
    /\/vast\./i,
    /\/vast\//i,
    /\/vpaid/i,
    /\/videoads/i,
    /\/preroll/i,
    /\/midroll/i,
    /\/postroll/i,
    /\/outstream/i,
    /\/instream/i,
    /\/video.*ad/i,
    // Retargeting
    /\/retarget/i,
    /\/remarketing/i,
    /\/rtb/i,
    /\/bidder/i,
    /\/header.*bidding/i,
    /\/hb\.js/i,
    // Crypto mining
    /coinhive/i,
    /cryptoloot/i,
    /cryptonight/i,
    /\/miner\./i,
    /\/coin.*miner/i,
    // Generic patterns
    /adstrack/i,
    /adnxs/i,
    /adserving/i,
    /addelivery/i,
    /adplatform/i,
    /admanager/i,
    /adobeid/i,
    /\/click\?/i,
    /\/impression\?/i,
    /\/conversion\?/i,
    /\/event\?/i,
    /\/t\.gif/i,
    /\/pixel\.gif/i,
    /\/1x1\./i,
    /\/empty\.gif/i,
    /\/spacer\.gif/i,
    /\/blank\.gif/i,
    /\/clear\.gif/i,
    /\/track\.gif/i,
    /\/b\.gif/i,
    // SSP/DSP patterns
    /openrtb/i,
    /\/ssp\//i,
    /\/dsp\//i,
    /\/exchange\//i,
    /\/auction/i,
    /\/bidding/i,
    /\/bid\.js/i,
    // Trackers
    /optimizely/i,
    /omniture/i,
    /webtrends/i,
    /clicktale/i,
    /crazyegg/i,
    /hotjar/i,
    /mouseflow/i,
    /inspectlet/i,
    /heap\.io/i,
    /heapanalytics/i,
    /amplitude/i,
    /mixpanel/i,
    /kissmetrics/i,
    /woopra/i,
    /pendo/i,
    /intercom/i,
    /drift/i,
    /hubspot/i,
    /marketo/i,
    /eloqua/i,
    /pardot/i,
    /sailthru/i,
    /braze/i,
    /iterable/i,
    /customer\.io/i,
    /clevertap/i,
    /moengage/i,
    /webengage/i,
    /insider/i,
    /pushwoosh/i,
    /onesignal/i,
    // Fingerprinting
    /fingerprintjs/i,
    /\/fp\.js/i,
    /\/fingerprint/i,
    /canvas.*fingerprint/i,
    /webgl.*fingerprint/i,
    /audio.*fingerprint/i,
    // Social tracking
    /platform\.twitter/i,
    /connect\.facebook/i,
    /platform\.linkedin/i,
    /platform\.instagram/i,
    /widgets\.pinterest/i,
    // CDN-hosted ads
    /cdn\.taboola/i,
    /cdn\.outbrain/i,
    /cdn\.mgid/i,
    /cdn\.revcontent/i,
    /widgets\.outbrain/i,
    /widgets\.content-ad/i,
    // Anti-adblock
    /blockadblock/i,
    /fuckadblock/i,
    /adblock-notify/i,
    /anti.*adblock/i,
    /adblock.*detector/i,
    /detect.*adblock/i,
    // Consent/GDPR (optional but often used for tracking)
    /consensu\.org/i,
    /\/tcf\//i,
    /\/cmp\//i,
    /\/gdpr.*consent/i,
    // Sponsored content
    /sponsored/i,
    /native.*ad/i,
    /content.*recommendation/i,
    /related.*content/i,
    /around.*web/i,
    /promoted.*content/i,
    // Misc ad patterns
    /\.ad$/i,
    /\/ad$/i,
    /_ad\./i,
    /-ad\./i,
    /\.ad\./i,
    /ad_/i,
    /_ad_/i,
    /\?ad=/i,
    /&ad=/i,
    /ads_/i,
    /_ads_/i,
    /\/async_ads/i,
    /\/async-ads/i,
    /\/smart_ads/i,
    /\/smart-ads/i,
    /\/lazy_ads/i,
    /\/lazy-ads/i,
    /\/inject_ads/i,
    /\/inject-ads/i,
    /\/sidebar.*ad/i,
    /\/header.*ad/i,
    /\/footer.*ad/i,
    /\/leaderboard/i,
    /\/skyscraper/i,
    /\/rectangle/i,
    /\/interstitial/i,
    /\/overlay.*ad/i,
    /\/floating.*ad/i,
    /\/sticky.*ad/i,
    /\/expand.*ad/i,
    /\/wallpaper.*ad/i,
    /\/takeover/i,
    /\/skin.*ad/i,
];

// Resource types typically used for ads
const adResourceTypes = [
    'script',
    'image',
    'stylesheet',
    'xhr',
    'fetch',
    'sub_frame',
    'ping',
    'beacon'
];

class AdBlocker {
    constructor() {
        this.enabled = true;
        this.blockedCount = 0;
        this.blockedByTab = new Map();
        this.whitelist = new Set();

        // Whitelist essential Google domains that are required for functionality
        // Note: We don't whitelist youtube.com/googlevideo.com entirely to allow ad blocking
        this.addToWhitelist('google.com');
        this.addToWhitelist('googleapis.com');
        this.addToWhitelist('gstatic.com');
        this.addToWhitelist('googleusercontent.com');
        this.addToWhitelist('gmail.com');
        this.addToWhitelist('googlemail.com');
        // YouTube core domains - but we'll block ads via URL patterns
        // this.addToWhitelist('youtube.com'); // Not whitelisted - we need to block ads
        // this.addToWhitelist('googlevideo.com'); // Not whitelisted - we need to block ads
        this.addToWhitelist('youtu.be'); // Short links are usually not ads
        this.addToWhitelist('ytimg.com'); // Thumbnails and images
        this.addToWhitelist('ggpht.com'); // Google hosted images

        // Privacy-focused search engines - should never be blocked
        this.addToWhitelist('duckduckgo.com');
        this.addToWhitelist('ddg.co');
        this.addToWhitelist('ddg.gg');
        this.addToWhitelist('duck.com');
        this.addToWhitelist('brave.com');
        this.addToWhitelist('search.brave.com');
        this.addToWhitelist('startpage.com');
        this.addToWhitelist('ecosia.org');
        this.addToWhitelist('qwant.com');
        this.addToWhitelist('bing.com'); // Main Bing domain for search
    }

    /**
     * Check if a URL should be blocked
     * @param {string} url - The URL to check
     * @param {string} resourceType - Type of resource
     * @returns {boolean} - True if should be blocked
     */
    shouldBlock(url, resourceType = 'other') {
        if (!this.enabled) return false;
        if (!url) return false;

        try {
            const urlObj = new URL(url);
            const hostname = urlObj.hostname;
            const fullUrl = url.toLowerCase();

            // Check whitelist first - essential domains should never be blocked
            if (this.isWhitelisted(hostname)) {
                return false;
            }

            // Check against known ad domains with precise matching
            for (const adDomain of adDomains) {
                // Use exact match or subdomain matching
                // This ensures we only block the specific ad domain, not similar legitimate domains
                if (hostname === adDomain ||
                    hostname.endsWith('.' + adDomain)) {
                    // Additional check: make sure we're not blocking a whitelisted domain
                    if (!this.isWhitelisted(hostname)) {
                        return true;
                    }
                }
            }

            // Special handling for YouTube ads detection
            const isYouTubeDomain = hostname.includes('youtube.com') ||
                hostname.includes('googlevideo.com');

            // Block ads.youtube.com domain specifically
            if (hostname === 'ads.youtube.com' || hostname.endsWith('.ads.youtube.com')) {
                return true;
            }

            if (isYouTubeDomain) {
                // Block YouTube ads by detecting ad-specific patterns
                // YouTube ads have specific query parameters and paths
                if (fullUrl.includes('ctier=') || // Ad tier parameter
                    fullUrl.includes('adformat=') || // Ad format parameter
                    fullUrl.includes('ad_type=') || // Ad type parameter
                    fullUrl.includes('ad_break=') || // Ad break parameter
                    fullUrl.includes('ad_module=') || // Ad module parameter
                    fullUrl.includes('ad_system=') || // Ad system parameter
                    fullUrl.includes('ad_instream=') || // Instream ad parameter
                    fullUrl.includes('ad_overlay=') || // Overlay ad parameter
                    fullUrl.includes('ad_preroll=') || // Preroll ad parameter
                    fullUrl.includes('ad_midroll=') || // Midroll ad parameter
                    fullUrl.includes('ad_postroll=') || // Postroll ad parameter
                    fullUrl.includes('/get_video_info') && (fullUrl.includes('ad_') || fullUrl.includes('ctier')) || // Ad video info
                    fullUrl.includes('/ptracking') || // YouTube tracking for ads
                    fullUrl.includes('/pagead/') || // Google page ads
                    fullUrl.includes('/ads/') || // Ad paths
                    fullUrl.includes('/ad_') || // Ad-related paths
                    fullUrl.includes('doubleclick') || // DoubleClick ads
                    fullUrl.includes('googlesyndication') || // Google syndication ads
                    fullUrl.includes('/adservice') || // Ad service
                    (fullUrl.includes('videoplayback') && (fullUrl.includes('ctier') || fullUrl.includes('adformat') || fullUrl.includes('ad_type'))) || // Ad video playback
                    fullUrl.includes('&ad=') || // Ad query parameter
                    fullUrl.includes('?ad=') || // Ad query parameter
                    fullUrl.includes('&adformat=') || // Ad format
                    fullUrl.includes('&ctier=') || // Content tier (ads)
                    fullUrl.includes('&ad_type=') || // Ad type
                    fullUrl.includes('&ad_break=') || // Ad break
                    fullUrl.includes('&ad_module=') || // Ad module
                    fullUrl.includes('&ad_system=') || // Ad system
                    fullUrl.includes('&ad_instream=') || // Instream ad
                    fullUrl.includes('&ad_overlay=') || // Overlay ad
                    fullUrl.includes('&ad_preroll=') || // Preroll ad
                    fullUrl.includes('&ad_midroll=') || // Midroll ad
                    fullUrl.includes('&ad_postroll=') || // Postroll ad
                    fullUrl.includes('/advertising/') || // Advertising paths
                    fullUrl.includes('/ad-break') || // Ad break paths
                    fullUrl.includes('/ad-breaks') || // Ad breaks paths
                    fullUrl.includes('/ad_break') || // Ad break paths
                    fullUrl.includes('/ad_breaks') || // Ad breaks paths
                    fullUrl.includes('/instream') && fullUrl.includes('ad') || // Instream ads
                    fullUrl.includes('/overlay') && fullUrl.includes('ad') || // Overlay ads
                    fullUrl.includes('/sponsor') || // Sponsored content
                    fullUrl.includes('/promoted') || // Promoted content
                    fullUrl.includes('&of=') && fullUrl.includes('ad') || // Ad-related of parameter
                    fullUrl.includes('&oad=') || // Ad parameter
                    fullUrl.includes('&oadp=') || // Ad parameter
                    fullUrl.includes('&oadv=') || // Ad parameter
                    fullUrl.includes('&oadc=')) { // Ad parameter
                    return true;
                }
                // Allow legitimate YouTube content (videos, thumbnails, etc.)
                // These patterns indicate legitimate content, not ads
                // This check happens after ad detection, so legitimate content is allowed
            }

            // Check URL patterns for all other domains
            for (const pattern of adUrlPatterns) {
                // For Google domains (but not YouTube), be more careful
                const isGoogleDomain = hostname.includes('google.com') && !isYouTubeDomain;

                if (isGoogleDomain) {
                    // Only block obvious ad paths on Google domains
                    if (pattern.test(fullUrl) && (
                        fullUrl.includes('/ads/') ||
                        fullUrl.includes('/adservice') ||
                        fullUrl.includes('/pagead/') ||
                        fullUrl.includes('/adsystem') ||
                        fullUrl.includes('doubleclick') ||
                        fullUrl.includes('googlesyndication')
                    )) {
                        // Double-check it's actually an ad URL, not a core service
                        if (!fullUrl.includes('/api/') &&
                            !fullUrl.includes('/static/') &&
                            !fullUrl.includes('/client/') &&
                            !fullUrl.includes('/accounts/') &&
                            !fullUrl.includes('/search')) {
                            return true;
                        }
                    }
                } else {
                    // For all other domains, apply patterns normally
                    if (pattern.test(fullUrl)) {
                        return true;
                    }
                }
            }

            return false;
        } catch (e) {
            return false;
        }
    }

    /**
     * Check if a domain is whitelisted
     * @param {string} hostname 
     * @returns {boolean}
     */
    isWhitelisted(hostname) {
        for (const domain of this.whitelist) {
            if (hostname === domain || hostname.endsWith('.' + domain)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Add domain to whitelist
     * @param {string} domain 
     */
    addToWhitelist(domain) {
        this.whitelist.add(domain.toLowerCase());
    }

    /**
     * Remove domain from whitelist
     * @param {string} domain 
     */
    removeFromWhitelist(domain) {
        this.whitelist.delete(domain.toLowerCase());
    }

    /**
     * Get whitelist as array
     * @returns {string[]}
     */
    getWhitelist() {
        return Array.from(this.whitelist);
    }

    /**
     * Record a blocked request
     * @param {number} tabId - Tab identifier
     */
    recordBlocked(tabId) {
        this.blockedCount++;
        const current = this.blockedByTab.get(tabId) || 0;
        this.blockedByTab.set(tabId, current + 1);
    }

    /**
     * Get blocked count for a tab
     * @param {number} tabId 
     * @returns {number}
     */
    getBlockedCountForTab(tabId) {
        return this.blockedByTab.get(tabId) || 0;
    }

    /**
     * Reset count for a tab (on navigation)
     * @param {number} tabId 
     */
    resetTabCount(tabId) {
        this.blockedByTab.set(tabId, 0);
    }

    /**
     * Get total blocked count
     * @returns {number}
     */
    getTotalBlocked() {
        return this.blockedCount;
    }

    /**
     * Enable ad blocking
     */
    enable() {
        this.enabled = true;
    }

    /**
     * Disable ad blocking
     */
    disable() {
        this.enabled = false;
    }

    /**
     * Toggle ad blocking
     * @returns {boolean} New state
     */
    toggle() {
        this.enabled = !this.enabled;
        return this.enabled;
    }

    /**
     * Check if ad blocking is enabled
     * @returns {boolean}
     */
    isEnabled() {
        return this.enabled;
    }

    /**
     * Get stats
     * @returns {object}
     */
    getStats() {
        return {
            enabled: this.enabled,
            totalBlocked: this.blockedCount,
            blockedByTab: Object.fromEntries(this.blockedByTab)
        };
    }
}

module.exports = AdBlocker;
